# Generated by Django 4.1.7 on 2023-03-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_course', models.CharField(max_length=50, unique=True, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='О курсе')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО преподавателя')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='SpeakersWebinars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Начало вебинара')),
                ('time', models.TimeField(null=True, verbose_name='Длительность вебинара')),
                ('speaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.speakers')),
            ],
            options={
                'verbose_name': 'Дополнительная инофрмация про вебинар',
                'verbose_name_plural': 'Дополнительная инофрмация про вебинары',
            },
        ),
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_webinar', models.CharField(max_length=50, unique=True, verbose_name='Название вебинара')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('Сейчас идет', 'Сейчас идет'), ('Отменен', 'Отменен'), ('Завершен', 'Завершен')], default='Создан', max_length=20, verbose_name='Статус вебинара')),
                ('description', models.TextField(verbose_name='О вебинаре')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.courses')),
                ('speakers', models.ManyToManyField(through='crud.SpeakersWebinars', to='crud.speakers')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
            },
        ),
        migrations.AddField(
            model_name='speakerswebinars',
            name='webinar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.webinars'),
        ),
        migrations.CreateModel(
            name='SpeakersCoursesBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(verbose_name='Ставка преподавателя за час')),
                ('courses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.courses')),
                ('speaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.speakers')),
            ],
            options={
                'verbose_name': 'Ставка преподавателя',
                'verbose_name_plural': 'Ставки преподавателей',
            },
        ),
    ]
